MU-Enigma/Hacktoberfest_2021

- Problems/Level-2/Problem 2/README.md
- Problems/Level-2/Problem 3/README.md
- Problems/Level-2/Problem 4/README.md
Do any necessary changes you might want.
> Problem Statements

- Problems/Level-3/Problem 1/README.md
Corrected a typo Saying problem 1 as problem 5 in readme.md
> Problem 1 Level 3

- Problems/Level-3/Problem_3/YASH_PROBLEM_3.c
> Level3 Problem3 Solved

- Problems/Level-3/Problem_4/YASH_PROBLEM_4.c
> Level3 Problem4 Solved

- Problems/Level-3/Problem_6/YASH_PROBLEM_6.c
> Level3 Problem6 Solved

- Problems/Level-3/Problem_7/YASH_PROBLEM_7.c
> Level3 Problem7 Solved

- Problems/Level-1/Problem_4/Sayarnil_Problem4
- Problems/Level-1/Problem_4/Sayarnil_Problem4.java
Level 1 problem 4 .... thanks for reviewing this at your earliest
>  Lvl 1 problem 4 solved

- Problems/Level-1/Problem_5/Sayarnil_lvl1_problem5.java
Sayarnil solved lvl 1 problem 5 , hope you review at your earliest
>  lvl1 problem 5 solved Sayarnil

- Problems/Level-1/Problem_8/VarunReddy_Problem_8.c
> Solved Problem_8 in Level_1

- Problems/Level-1/Problem_2/manishkumar_problem_2.c
> solved problem 2 in level-1

- Problems/Level-1/Problem_8/Manishkumar_problem_8.c
> Solved problem-8 of level-1

- Problems/Level-1/Problem_1/Manishkumar_problem_1.py
> Solved problem-1 of level-1

- Problems/Level-1/Problem_4/Manishkumar_problem_4.cpp
> Solved problem-4 of level-1

- Problems/Level-1/Problem_2/PraneethSai_Problem_2.c
> Solved Problem_2 in Level-1

- Problems/Level-1/Problem_3/PraneethSai_Problem_3.c
>  Solved Problem_3 in Level -1

- Problems/Level-1/Problem_4/PraneethSai_Problem_4.c
>  Solved Problem_4 in Level-1

- Problems/Level-1/Problem_5/PraneethSai_Problem_5.c
>  Solved Problem_5 in Level 1

- Problems/Level-1/Problem_6/PraneethSai_Problem_6.c
>  Solved Problem_6 in Level-1

- Problems/Level-1/Problem_1/PranavSunil_Level1_Problem1.c
> Level1 Problem1 Solved

- Problems/Level-1/Problem_2/PranavSunil_Level1_Problem2.c
> Level1 Problem2 Solved

- Problems/Level-1/Problem_4/PranavSunil_Level1_Problem4.c
> Level1 Problem4 Solved

- Buggy_Codes/code_1/PranavSunil_BuggyCode1.c
> Buggycode1 Solved
